"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.StringT = exports.FalseT = exports.Default = exports.BooleanT = exports.findKeys = exports.valueEqual = exports.keyEqual = exports.deepEqual = exports.objectToString = exports.coinChange = exports.verifyHeading3 = exports.verifyHeading2 = exports.verifyHeading1 = exports.sanitize = exports.headingToHTML = exports.state = exports.nothing = exports.maybe = exports.monad_list = exports.just = exports.future = exports.either = exports.list = exports.zeroStringArray = exports.zeroNumberArray = exports.sortedArray = exports.rotateRight = exports.rotateLeft = exports.reverseSortedArray = exports.resetArray = exports.randomMatrix = exports.randomArray = exports.median = exports.defaultArray = exports.arrayMayGet = exports.NumberMaxHeap = exports.NumberMinHeap = exports.readStream = exports.LinuxDirectoryNode = exports.isMac = exports.isWindows = exports.isLinux = exports.osname = exports.platform = exports.hash512 = exports.hash256 = exports.fs = exports.Conversions = exports.canvas = exports.base64 = void 0;
exports.TrueT = void 0;
const index_1 = require("./node/index");
Object.defineProperty(exports, "fs", { enumerable: true, get: function () { return index_1.fs; } });
Object.defineProperty(exports, "hash256", { enumerable: true, get: function () { return index_1.hash256; } });
Object.defineProperty(exports, "hash512", { enumerable: true, get: function () { return index_1.hash512; } });
Object.defineProperty(exports, "platform", { enumerable: true, get: function () { return index_1.platform; } });
Object.defineProperty(exports, "osname", { enumerable: true, get: function () { return index_1.osname; } });
Object.defineProperty(exports, "isLinux", { enumerable: true, get: function () { return index_1.isLinux; } });
Object.defineProperty(exports, "isWindows", { enumerable: true, get: function () { return index_1.isWindows; } });
Object.defineProperty(exports, "isMac", { enumerable: true, get: function () { return index_1.isMac; } });
Object.defineProperty(exports, "readStream", { enumerable: true, get: function () { return index_1.readStream; } });
Object.defineProperty(exports, "LinuxDirectoryNode", { enumerable: true, get: function () { return index_1.LinuxDirectoryNode; } });
const { base64 } = require("./string/index.js");
exports.base64 = base64;
const { defaultArray, list, median, randomArray, randomMatrix, resetArray, reverseSortedArray, rotateLeft, rotateRight, sortedArray, zeroNumberArray, zeroStringArray, arrayMayGet, } = require("./array/index.js");
exports.defaultArray = defaultArray;
exports.list = list;
exports.median = median;
exports.randomArray = randomArray;
exports.randomMatrix = randomMatrix;
exports.resetArray = resetArray;
exports.reverseSortedArray = reverseSortedArray;
exports.rotateLeft = rotateLeft;
exports.rotateRight = rotateRight;
exports.sortedArray = sortedArray;
exports.zeroNumberArray = zeroNumberArray;
exports.zeroStringArray = zeroStringArray;
exports.arrayMayGet = arrayMayGet;
const { NumberMinHeap, NumberMaxHeap } = require("./heap/index.js");
exports.NumberMinHeap = NumberMinHeap;
exports.NumberMaxHeap = NumberMaxHeap;
const BooleanT = require("./primitives/boolean");
exports.BooleanT = BooleanT;
const Default = require("./primitives/default");
exports.Default = Default;
const FalseT = require("./primitives/false");
exports.FalseT = FalseT;
const string_1 = __importDefault(require("./primitives/string"));
exports.StringT = string_1.default;
const TrueT = require("./primitives/true");
exports.TrueT = TrueT;
const { canvas } = require("./canvas/canvas");
exports.canvas = canvas;
const Conversions = require("./conversions/conversions");
exports.Conversions = Conversions;
const { objectToString, deepEqual, keyEqual, valueEqual, findKeys } = require("./object/object");
exports.objectToString = objectToString;
exports.deepEqual = deepEqual;
exports.keyEqual = keyEqual;
exports.valueEqual = valueEqual;
exports.findKeys = findKeys;
const { nothing, just, maybe, either, list: monad_list, future, state } = require("./functional/monad");
exports.nothing = nothing;
exports.just = just;
exports.maybe = maybe;
exports.either = either;
exports.monad_list = monad_list;
exports.future = future;
exports.state = state;
const { headingToHTML, sanitize, verifyHeading1, verifyHeading2, verifyHeading3 } = require("./markdown/markdown.js");
exports.headingToHTML = headingToHTML;
exports.sanitize = sanitize;
exports.verifyHeading1 = verifyHeading1;
exports.verifyHeading2 = verifyHeading2;
exports.verifyHeading3 = verifyHeading3;
const coinChange = require("./misc/coinChange");
exports.coinChange = coinChange;
