import { filterReduce, foldl, foldr, take, tail, head } from "./fns/list.js";
import {
    arrayToString,
    defaultArray,
    isArray,
    isArraylike,
    median,
    randomArray,
    randomMatrix,
    resetArray,
    reverseSortedArray,
    rotateLeft,
    rotateRight,
    sortedArray,
    zeroNumberArray,
    zeroStringArray,
    filterOut,
    filterIn,
    inplaceFilterOut,
    inplaceFilterIn,
    chunk,
    filterInStream,
    filterOutStream
} from "./fns/array.js";

const list = { filterReduce, foldl, foldr, take, tail, head };

export {
    arrayToString,
    chunk,
    defaultArray,
    filterIn,
    filterInStream,
    filterOut,
    filterOutStream,
    inplaceFilterIn,
    inplaceFilterOut,
    isArray,
    isArraylike,
    list,
    median,
    randomArray,
    randomMatrix,
    resetArray,
    reverseSortedArray,
    rotateLeft,
    rotateRight,
    sortedArray,
    zeroNumberArray,
    zeroStringArray,
};
